// export const myprofile = [
//   {
//     t: 'input',
//     f: 'PartitionKey',
//     id: 'PartitionKey',
//     p: 'PartitionKey',
//     l: 'PartitionKey',
//   },
//   {
//     t: 'input',
//     f: 'RowKey',
//     id: 'RowKey',
//     p: 'RowKey',
//     l: 'RowKey',
//   },
//   {
//     t: 'input',
//     f: 'totalFees',
//     id: 'totalFees',
//     p: 'Enter Total Fees',
//     l: 'Total Fees:',
//   },
//   {
//     t: 'input',
//     f: 'paidFees',
//     id: 'paidFees',
//     p: 'Enter Paid Fees',
//     l: 'Paid Fees:',
//   },
//   {
//     t: 'input',
//     f: 'remainingFees',
//     id: 'renaminingFees',
//     p: 'Enter Remaining Fees',
//     l: 'Remaining Fees:',
//   },
//   {
//     t: 'input',
//     f: 'monthlyInstallement',
//     id: 'monthlyInstallement',
//     p: 'Enter Monthly Installement',
//     l: 'Monthly Installement:',
//   },
//   {
//     t: 'input',
//     f: 'paidUpto',
//     id: 'paidUpto',
//     p: ' Enter last paid month',
//     l: 'Paid upto:',
//     },
//     {
//     t: 'input',
//     f: 'lastPaidOn',
//     id: 'lastPaidOn',
//     p: ' Enter last paid date',
//     l: 'Last Paid on:',
//     },
//       {
//     t: 'input',
//     f: 'lastDate',
//     id: 'lastDate',
//     p: ' Enter last date to pay installements',
//     l: 'Last date to pay next installement:',
//   }