export const myprofile = [
  {
    t: 'input',
    f: 'PartitionKey',
    id: 'PartitionKey',
    p: 'PartitionKey',
    l: 'PartitionKey',
  },
  {
    t: 'input',
    f: 'RowKey',
    id: 'RowKey',
    p: 'RowKey',
    l: 'RowKey',
  },
  {
    t: 'input',
    f: 'name',
    id: 'name',
    p: 'Enter Name',
    l: 'Name',
  },
  {
    t: 'input',
    f: 'myClass',
    id: 'class',
    p: 'Enter Class',
    l: 'Class',
  },
  {
    t: 'input',
    f: 'dob',
    id: 'dob',
    p: 'Enter date of birth',
    l: 'D.O.B',
  },
  {
    t: 'input',
    f: 'age',
    id: 'age',
    p: 'Enter Age',
    l: 'Age',
  },
  {
    t: 'input',
    f: ' bloodGroup',
    id: 'blood_group',
    p: ' Enter blood group',
    l: 'Blood Group',
  },
  {
    t: 'input',
    f: 'contact1',
    id: 'contact1',
    p: 'Enter Contact Number',
    l: 'Contact Number',
  },
  {
    t: 'input',
    f: 'contact2',
    id: 'contact2',
    p: ' Enter Alternate Contact Number',
    l: 'Alternate Contact Number',
  },
  {
    t: 'input',
    f: 'email1',
    id: 'email1',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
  {
    t: 'input',
    f: 'email2',
    id: 'email2',
    p: 'Enter Alternate Email Address',
    l: 'Alternate Email Address',
  },
  {
    t: 'input',
    f: 'address',
    id: 'address',
    p: 'Enter  Address',
    l: 'Address',
  },
  {
    t: 'input',
    f: 'f_name',
    id: 'f_name',
    p: "Enter Father's Name",
    l: "Father's Name",
  },
  {
    t: 'input',
    f: 'f_contact',
    id: 'f_contact',
    p: "Enter Father's contact No",
    l: 'Contact Number',
  },
  {
    t: 'input',
    f: 'f_email',
    id: 'f_email',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
  {
    t: 'input',
    f: 'm_name',
    id: 'm_name',
    p: "Enter Mother's Name",
    l: "Mother's Name",
  },
  {
    t: 'input',
    f: 'm_contact',
    id: 'm_contact',
    p: "Enter Mother's contact No",
    l: 'Contact Number',
  },
  {
    t: 'input',
    f: 'm_email',
    id: 'm_email',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
]
