export const loginform = [
  {
    t: 'input',
    f: 'email',
    id: 'email',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
  {
    t: 'input',
    f: 'password',
    id: 'password',
    p: 'Enter Password',
    l: 'Password',
  },

  {
    type: 'Radio',
    label: 'Gender',
    name: 'gender',
    params: {
      options: [
        {
          value: '1',
          label: 'Gender',
        },
        {
          value: '2',
          label: 'Gender',
        },
        {
          value: '3',
          label: 'Gender',
        },
      ],
    },
  },
]
export const myprofile = [
  {
    type: 'input',
    f: 'Name',
    id: 'name',
    p: 'Enter Name',
    l: 'Name',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'std',
    id: 'std',
    p: 'Enter Standard',
    l: 'Standard',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'section',
    id: 'section',
    p: 'Enter Section',
    l: 'Section',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'date',
    f: 'dob',
    id: 'dob',
    p: 'Enter date of birth',
    l: 'D.O.B',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'age',
    id: 'age',
    p: 'Enter Age',
    l: 'Age',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: ' bloodGroup',
    id: 'blood_group',
    p: ' Enter blood group',
    l: 'Blood Group',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'contact1',
    id: 'contact1',
    p: 'Enter Contact Number',
    l: 'Contact Number',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'contact2',
    id: 'contact2',
    p: ' Enter Alternate Contact Number',
    l: 'Alternate Contact Number',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'email1',
    id: 'email1',
    p: 'Enter Email Address',
    l: 'Email Address',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'email2',
    id: 'email2',
    p: 'Enter Alternate Email Address',
    l: 'Alternate Email Address',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'address',
    id: 'address',
    p: 'Enter  Address',
    l: 'Address',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'f_name',
    id: 'f_name',
    p: "Enter Father's Name",
    l: "Father's Name",
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'f_contact',
    id: 'f_contact',
    p: "Enter Father's contact No",
    l: 'Contact Number',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'f_email',
    id: 'f_email',
    p: 'Enter Email Address',
    l: 'Email Address',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'm_name',
    id: 'm_name',
    p: "Enter Mother's Name",
    l: "Mother's Name",
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'm_contact',
    id: 'm_contact',
    p: "Enter Mother's contact No",
    l: 'Contact Number',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'm_email',
    id: 'm_email',
    p: 'Enter Email Address',
    l: 'Email Address',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
]
export const signupform = [
  {
    t: 'input',
    f: 'email',
    id: 'email',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
  {
    t: 'input',
    f: 'password',
    id: 'password',
    p: 'Enter Password',
    l: 'Password',
  },
]
export const fees = [
  {
    t: 'input',
    f: 'PartitionKey',
    id: 'PartitionKey',
    p: 'PartitionKey',
    l: 'PartitionKey',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'RowKey',
    id: 'RowKey',
    p: 'RowKey',
    l: 'RowKey',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'totalFees',
    id: 'totalFees',
    p: 'Enter Total Fees',
    l: 'Total Fees:',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'paidFees',
    id: 'paidFees',
    p: 'Enter Paid Fees',
    l: 'Paid Fees:',
    class:'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'remainingFees',
    id: 'remainingFees',
    p: 'Enter Remaining Fees',
    l: 'Remaining Fees:',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'noOfInstallment',
    id: 'noOfInstallment',
    p: 'Enter Number of Installment',
    l: 'Number of Installment:',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'monthlyInstallement',
    id: 'monthlyInstallement',
    p: 'Enter Monthly Installement',
    l: 'Monthly Installement:',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'paidUpto',
    id: 'paidUpto',
    p: ' Enter last paid month',
    l: 'Paid upto:',

    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'lastPaidOn',
    id: 'lastPaidOn',
    p: ' Enter last paid date',
    l: 'Last Paid on:',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'lastDate',
    id: 'lastDate',
    p: ' Enter last date to pay installements',
    l: 'Last date to pay next installement:',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
]
export const notification = [
  {
    t: 'input',
    f: 'RowKey',
    id: 'RowKey',
    p: ' Enter Notification Number',
    l: ' Notification Number',
    class: 'col-5',
  },
  {
    t: 'date',
    f: 'date',
    id: 'date',
    p: 'Enter Date',
    l: 'Date',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'recipient',
    id: 'recipient',
    p: 'Enter recipient',
    l: 'Recipient',
    class: 'col-10',
  },
  {
    t: 'textarea',
    f: 'notification',
    id: 'notification',
    p: 'Enter content of notification....',
    l: 'Notification:',
    rows: '8',
    cols: '150',
  },
]
export const complain = [
  {
    t: 'input',
    f: 'PartitionKey',
    id: 'PartitionKey',
    p: 'PartitionKey',
    l: 'PartitionKey',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'RowKey',
    id: 'RowKey',
    p: 'RowKey',
    l: 'RowKey',
    class: 'col-5',
  },

  {
    t: 'text',
    f: 'to',
    id: 'to',
    p: 'To',
    l: 'To:',
    class: 'col-10',
  },
  {
    t: 'textarea',
    f: 'description',
    id: 'description',
    p: 'Write your Complaint....',
    l: 'Complaint:',
    rows: '8',
    cols: '150',
   
  },
]


export const create_role = [
  {
    t: 'input',
    f: 'pname',
    id: 'name',
    p: 'Enter your name',
    l: 'Name',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'pdob',
    id: 'dob',
    p: 'Enter your date of birth',
    l: 'D.O.B',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'gender',
    id: 'gender',
    p: 'Enter gender',
    l: 'Gender',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'pms',
    id: 'ms',
    p: 'Enter your Maritial status',
    l: 'Maritial Status',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'page',
    id: 'age',
    p: 'Enter your Age',
    l: 'Age',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'page',
    id: 'contact1',
    p: 'Enter contact no.',
    l: 'Contact Number',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'page',
    id: 'contact2',
    p: 'Enter alternate contact no.',
    l: 'Alternate Contact No.',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'page',
    id: 'email',
    p: 'Enter email.',
    l: 'Email address',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },

  {
    t: 'input',
    f: 'page',
    id: 'qualification',
    p: 'Enter qualification',
    l: 'Qualification',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'page',
    id: 'work_experience',
    p: 'Enter Work Experience',
    l: 'Work Experience',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'page',
    id: 'designation',
    p: 'Designation',
    l: 'Designation',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'page',
    id: 'department',
    p: 'Department',
    l: 'Department',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
  {
    t: 'input',
    f: 'page',
    id: 'address',
    p: 'Enter your address',
    l: 'Address',
    class: 'col-lg-4,col-md-6,col-sm-12',
  },
]
export const teachertimetable = [
  {
    type: 'input',
    f: 'class',
    id: 'class',
    p: 'Class',
    l: 'class',
    class: 'col-lg-3,col-md-2,col-sm-1',
  },

  {
    type: 'input',
    f: 'teachersection',
    id: 'teachersection',
    p: 'Section',
    l: 'section',
    class: 'col-lg-3,col-md-2,col-sm-1',
  },
  {
    type: 'input',
    f: 'RowKey',
    id: 'RowKey',
    p: 'number',
    l: 'Number',
    class: 'col-lg-3,col-md-2,col-sm-1',
  },
  {
    type: 'input',
    f: 'days',
    id: 'days',
    p: 'Enter Days',
    l: 'Days',
    class: 'col-lg-3,col-md-2,col-sm-1',
  },
  {
    type: 'input',
    f: 'lecture1',
    id: 'lecture1',
    p: 'Enter lecture time',
    l: ' Lecture time',
    class: 'col-5',
  },

  {
    type: 'input',
    f: 'subject1',
    id: 'subject1',
    p: 'subject',
    l: 'Subject1',
    class: 'col-5',
  },
  {
    type: 'input',
    f: 'lecture2',
    id: 'lecture2',
    p: 'Enter lecture time',
    l: ' Lecture time',
    class: 'col-5',
  },
  {
    type: 'input',
    f: 'subject2',
    id: 'subject2',
    p: 'subject2',
    l: 'Subject2',
    class: 'col-5',
  },
  {
    type: 'input',
    f: 'lecture3',
    id: 'lecture3',
    p: 'Enter lecture time',
    l: ' Lecture time',
    class: 'col-5',
  },
  {
    type: 'input',
    f: 'subject3',
    id: 'subject3',
    p: 'subject3',
    l: 'Subject3',
    class: 'col-5',
  },
  {
    type: 'input',
    f: 'lecture4',
    id: 'lecture4',
    p: 'Enter lecture time',
    l: ' Lecture time',
    class: 'col-5',
  },
  {
    type: 'input',
    f: 'subject4',
    id: 'subject4',
    p: 'subject4',
    l: 'subject4',
    class: 'col-5',
  },
  {
    type: 'input',
    f: 'lecture5',
    id: 'lecture5',
    p: 'Enter lecture time',
    l: ' Lecture time',
    class: 'col-5',
  },
  {
    type: 'input',
    f: 'subject5',
    id: 'subject5',
    p: 'subject5',
    l: 'Subject5',
    class: 'col-5',
  },
]
