export const form1 = [
  {
    t: 'Input',
    l: 'First Name',
    n: 'firstname',
    v: 'required',
    p: 'EnterFirst Name',
  },
  {
    type: 'Input',
    placeholder: 'EnterFirst Name',
    label: 'Last Name',
    name: 'lastname',
    validation: 'required',
    placeholder: 'EnterFirst Name',
  },
  {
    type: 'Input',
    label: 'Email',
    name: 'email',
    validation: 'required|email',
    placeholder: 'EnterFirst Name',
  },
  {
    type: 'Checkbox',
    label: 'Do you like Vuejs?',
    name: 'likeVue',
  },
  {
    type: 'Radio',
    label: 'Gender',
    name: 'gender',
    params: {
      options: [
        {
          value: '1',
          label: 'Gender',
        },
        {
          value: '2',
          label: 'Gender',
        },
        {
          value: '3',
          label: 'Gender',
        },
      ],
    },
  },
]
export const myprofile = [
  {
    type: 'input',
    f: 'PartitionKey',
    id: 'PartitionKey',
    p: 'PartitionKey',
    l: 'PartitionKey',
   
  },
  {
    type: 'input',
    f: 'RowKey',
    id: 'RowKey',
    p: 'RowKey',
    l: 'RowKey',
  },
  {
    type: 'text',
    f: 'Name',
    id: 'name',
    p: 'Enter Name',
    l: 'Name',
    readOnly:true,
  },
  {
    t: 'text',
    f: 'Class',
    id: 'class',
    p: 'Enter Class',
    l: 'Class',
  },
  {
    t: 'number',
    f: 'dob',
    id: 'dob',
    p: 'Enter date of birth',
    l: 'D.O.B',
  },
  {
    t: 'number',
    f: 'age',
    id: 'age',
    p: 'Enter Age',
    l: 'Age',
  },
  {
    t: 'input',
    f: ' bloodGroup',
    id: 'blood_group',
    p: ' Enter blood group',
    l: 'Blood Group',
  },
  {
    t: 'tel',
    f: 'contact1',
    id: 'contact1',
    p: 'Enter Contact Number',
    l: 'Contact Number',
  },
  {
    t: 'tel',
    f: 'contact2',
    id: 'contact2',
    p: ' Enter Alternate Contact Number',
    l: 'Alternate Contact Number',
  },
  {
    t: 'email',
    f: 'email1',
    id: 'email1',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
  {
    t: 'email',
    f: 'email2',
    id: 'email2',
    p: 'Enter Alternate Email Address',
    l: 'Alternate Email Address',
  },
  {
    t: 'input',
    f: 'address',
    id: 'address',
    p: 'Enter  Address',
    l: 'Address',
  },
  {
    t: 'input',
    f: 'f_name',
    id: 'f_name',
    p: "Enter Father's Name",
    l: "Father's Name",
  },
  {
    t: 'tel',
    f: 'f_contact',
    id: 'f_contact',
    p: "Enter Father's contact No",
    l: 'Contact Number',
  },
  {
    t: 'email',
    f: 'f_email',
    id: 'f_email',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
  {
    t: 'input',
    f: 'm_name',
    id: 'm_name',
    p: "Enter Mother's Name",
    l: "Mother's Name",
  },
  {
    t: 'tel',
    f: 'm_contact',
    id: 'm_contact',
    p: "Enter Mother's contact No",
    l: 'Contact Number',
    class: 'col-4',
  },
  {
    t: 'email',
    f: 'm_email',
    id: 'm_email',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
]
export const signupform = [
  {
    t: 'input',
    f: 'email',
    id: 'email',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
  {
    t: 'input',
    f: 'password',
    id: 'password',
    p: 'Enter Password',
    l: 'Password',
  },
]
export const fees = [
  // {
  //   t: 'input',
  //   f: 'PartitionKey',
  //   id: 'PartitionKey',
  //   p: 'PartitionKey',
  //   l: 'PartitionKey',
  // },
  // {
  //   t: 'input',
  //   f: 'RowKey',
  //   id: 'RowKey',
  //   p: 'RowKey',
  //   l: 'RowKey',
  // },
  {
    t: 'input',
    f: 'totalFees',
    id: 'totalFees',
    p: 'Enter Total Fees',
    l: 'Total Fees:',
    class: 'col-5',
  
    
  },
  {
    t: 'input',
    f: 'paidFees',
    id: 'paidFees',
    p: 'Enter Paid Fees',
    l: 'Paid Fees:',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'remainingFees',
    id: 'renaminingFees',
    p: 'Enter Remaining Fees',
    l: 'Remaining Fees:',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'monthlyInstallement',
    id: 'monthlyInstallement',
    p: 'Enter Monthly Installement',
    l: 'Monthly Installement:',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'paidUpto',
    id: 'paidUpto',
    p: ' Enter last paid month',
    l: 'Paid upto:',
    
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'lastPaidOn',
    id: 'lastPaidOn',
    p: ' Enter last paid date',
    l: 'Last Paid on:',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'lastDate',
    id: 'lastDate',
    p: ' Enter last date to pay installements',
    l: 'Last date to pay next installement:',
    class: 'col-10',
  },
]
export const notification = [
  {
    t: 'input',
    f: 'PartitionKey',
    id: 'PartitionKey',
    p: 'PartitionKey',
    l: 'PartitionKey',
  },
  { t: 'input', f: 'RowKey', id: 'RowKey', p: 'RowKey', l: 'RowKey' },
  { t: 'input', f: 'fto', id: 'to', p: 'to', l: 'To:' },
  {
    t: 'textarea',
    f: 'fnotification',
    id: 'notification',
    p: 'Enter content of notification....',
    l: 'Notification:',
  },
]