export const loginform = [
  {
    t: 'input',
    f: 'email',
    id: 'email',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
  {
    t: 'input',
    f: 'password',
    id: 'password',
    p: 'Enter Password',
    l: 'Password',
  },

  {
    type: 'Radio',
    label: 'Gender',
    name: 'gender',
    params: {
      options: [
        {
          value: '1',
          label: 'Gender',
        },
        {
          value: '2',
          label: 'Gender',
        },
        {
          value: '3',
          label: 'Gender',
        },
      ],
    },
  },
]
export const myprofile = [
  {
    t: 'input',
    f: 'PartitionKey',
    id: 'PartitionKey',
    p: 'PartitionKey',
    l: 'PartitionKey',
  },
  {
    t: 'input',
    f: 'RowKey',
    id: 'RowKey',
    p: 'RowKey',
    l: 'RowKey',
  },
  {
    type: 'input',
    f: 'Name',
    id: 'name',
    p: 'Enter Name',
    l: 'Name',
  },
  {
    t: 'input',
    f: 'class',
    id: 'class',
    p: 'Enter Class',
    l: 'Class',
  },
  {
    t: 'input',
    f: 'dob',
    id: 'dob',
    p: 'Enter date of birth',
    l: 'D.O.B',
  },
  {
    t: 'input',
    f: 'age',
    id: 'age',
    p: 'Enter Age',
    l: 'Age',
  },
  {
    t: 'input',
    f: ' bloodGroup',
    id: 'blood_group',
    p: ' Enter blood group',
    l: 'Blood Group',
  },
  {
    t: 'input',
    f: 'contact1',
    id: 'contact1',
    p: 'Enter Contact Number',
    l: 'Contact Number',
  },
  {
    t: 'input',
    f: 'contact2',
    id: 'contact2',
    p: ' Enter Alternate Contact Number',
    l: 'Alternate Contact Number',
  },
  {
    t: 'input',
    f: 'email1',
    id: 'email1',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
  {
    t: 'input',
    f: 'email2',
    id: 'email2',
    p: 'Enter Alternate Email Address',
    l: 'Alternate Email Address',
  },
  {
    t: 'input',
    f: 'address',
    id: 'address',
    p: 'Enter  Address',
    l: 'Address',
  },
  {
    t: 'input',
    f: 'f_name',
    id: 'f_name',
    p: "Enter Father's Name",
    l: "Father's Name",
  },
  {
    t: 'input',
    f: 'f_contact',
    id: 'f_contact',
    p: "Enter Father's contact No",
    l: 'Contact Number',
  },
  {
    t: 'input',
    f: 'f_email',
    id: 'f_email',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
  {
    t: 'input',
    f: 'm_name',
    id: 'm_name',
    p: "Enter Mother's Name",
    l: "Mother's Name",
  },
  {
    t: 'input',
    f: 'm_contact',
    id: 'm_contact',
    p: "Enter Mother's contact No",
    l: 'Contact Number',
    class: 'col-4',
  },
  {
    t: 'input',
    f: 'm_email',
    id: 'm_email',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
]
export const signupform = [
  {
    t: 'input',
    f: 'email',
    id: 'email',
    p: 'Enter Email Address',
    l: 'Email Address',
  },
  {
    t: 'input',
    f: 'password',
    id: 'password',
    p: 'Enter Password',
    l: 'Password',
  },
]
export const fees = [
  {
    t: 'input',
    f: 'PartitionKey',
    id: 'PartitionKey',
    p: 'PartitionKey',
    l: 'PartitionKey',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'RowKey',
    id: 'RowKey',
    p: 'RowKey',
    l: 'RowKey',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'totalFees',
    id: 'totalFees',
    p: 'Enter Total Fees',
    l: 'Total Fees:',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'paidFees',
    id: 'paidFees',
    p: 'Enter Paid Fees',
    l: 'Paid Fees:',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'remainingFees',
    id: 'remainingFees',
    p: 'Enter Remaining Fees',
    l: 'Remaining Fees:',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'monthlyInstallement',
    id: 'monthlyInstallement',
    p: 'Enter Monthly Installement',
    l: 'Monthly Installement:',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'paidUpto',
    id: 'paidUpto',
    p: ' Enter last paid month',
    l: 'Paid upto:',

    class: 'col-5',
  },
  {
    t: 'input',
    f: 'lastPaidOn',
    id: 'lastPaidOn',
    p: ' Enter last paid date',
    l: 'Last Paid on:',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'lastDate',
    id: 'lastDate',
    p: ' Enter last date to pay installements',
    l: 'Last date to pay next installement:',
    class: 'col-10',
  },
]
export const notification = [
  {
    t: 'input',
    f: 'RowKey',
    id: 'RowKey',
    p: ' Enter Notification Number',
    l: ' Notification Number',
    class: 'col-5',
  },
  {
    t: 'date',
    f: 'date',
    id: 'date',
    p: 'Enter Date',
    l: 'Date',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'recipient',
    id: 'recipient',
    p: 'Enter recipient',
    l: 'Recipient',
    class: 'col-10',
  },
  {
    t: 'textarea',
    f: 'notification',
    id: 'notification',
    p: 'Enter content of notification....',
    l: 'Notification:',
    class: 'col-10',
    style: 'height:250px',
  },
]
export const complain = [
  {
    t: 'input',
    f: 'PartitionKey',
    id: 'PartitionKey',
    p: 'PartitionKey',
    l: 'PartitionKey',
    class: 'col-5',
  },
  {
    t: 'input',
    f: 'RowKey',
    id: 'RowKey',
    p: 'RowKey',
    l: 'RowKey',
    class: 'col-5',
  },

  {
    t: 'text',
    f: 'to',
    id: 'to',
    p: 'To',
    l: 'To:',
    class: 'col-10',
  },
  {
    t: 'textarea',
    f: 'description',
    id: 'description',
    p: 'Write your Complaint....',
    l: 'Complaint:',
    class: 'col-10',
    style: 'height:150px',
  },
]
export const getfees = [
  {
    t: 'input',
    f: 'PartitionKey1',
    id: 'PartitionKey1',
    p: 'PartitionKey',
    l: 'PartitionKey',
  },
  {
    t: 'input',
    f: 'RowKey1',
    id: 'RowKey1',
    p: 'RowKey',
    l: 'RowKey',
  },
]
export const installement = [
  // {
  //   t: 'input',
  //   f: 'PartitionKey',
  //   id: 'PartitionKey',
  //   p: 'PartitionKey',
  //   l: 'PartitionKey',
  //   class: 'col-5',
  // },
  // {
  //   t: 'input',
  //   f: 'RowKey',
  //   id: 'RowKey',
  //   p: 'RowKey',
  //   l: 'RowKey',
  //   class: 'col-5',
  // },
  {
    t: 'text',
    f: 'installmentNo',
    id: 'installmentNo',
    p: 'Installment No',
    l: ' Enter Installment No:',
    class: 'col-3',
  },
  {
    t: 'text',
    f: 'amount',
    id: 'amount',
    p: 'Enter Installment Amount',
    l: 'Installment Amount',
    class: 'col-3',
  },

  {
    t: 'text',
    f: 'dateofpayment',
    id: 'dateofpayment',
    p: 'Enter Date of Payment',
    l: ' Date of Payment',
    class: 'col-3',
  },
]
export const create_role = [
  {
    t: 'input',
    f: 'PartitionKey',
    id: 'PartitionKey',
    p: 'PartitionKey',
    l: 'PartitionKey',
  },
  { t: 'input', f: 'RowKey', id: 'RowKey', p: 'RowKey', l: 'RowKey' },
  { t: 'input', f: 'pname', id: 'name', p: 'Enter your name', l: 'Name' },
  {
    t: 'input',
    f: 'pdob',
    id: 'dob',
    p: 'Enter your date of birth',
    l: 'D.O.B',
  },
  {
    t: 'input',
    f: 'pms',
    id: 'ms',
    p: 'Enter your Maritial status',
    l: 'Maritial Status',
  },
  { t: 'input', f: 'page', id: 'age', p: 'Enter your Age', l: 'Age' },
  {
    t: 'input',
    f: 'page',
    id: 'contact1',
    p: 'Enter contact no.',
    l: 'Contact Number',
  },
  {
    t: 'input',
    f: 'page',
    id: 'contact2',
    p: 'Enter alternate contact no.',
    l: 'Alternate Contact No.',
  },
  {
    t: 'input',
    f: 'page',
    id: 'email',
    p: 'Enter email.',
    l: 'Email address',
  },
  // {
  //   t: 'radio',
  //   f: 'powner',
  //   id: 'gender',
  //   p: '',
  //   l: 'Gender',
  //   menu: ['m', 'f', 'o'],
  // },
  {
    t: 'input',
    f: 'page',
    id: 'qualification',
    p: 'Enter qualification',
    l: 'Qualification',
  },
  {
    t: 'input',
    f: 'page',
    id: 'work',
    p: 'Enter work Experiance',
    l: 'work experiance',
  },
  { t: 'input', f: 'page', id: 'designation', p: 'Designation', l: 'Designation' },
  { t: 'input', f: 'page', id: 'department', p: 'Department', l: 'Department' },
  {
    t: 'input',
    f: 'page',
    id: 'address',
    p: 'Enter your address',
    l: 'Address',
  },
  { t: 'input', f: 'page', id: 'joindate', p: ' Enter join date', l: 'Join date' },
]


